port: 8080

endpoints:
  - name: "Google"
    url: "https://www.google.com"
    interval: 30s
    timeout: 5s
    down_threshold: 3

  - name: "My Test API"
    url: "https://httpstat.us/200"
    interval: 60s
    timeout: 10s
    down_threshold: 2

  - name : "Movie finder app"
    url: "https://movie-finder-app-tau.vercel.app"
    interval: 60s
    timeout: 10s
    down_threshold: 3